services:
  - type: web
    name: dental-api
    env: node
    buildCommand: npm ci
    startCommand: npm run start:prod
    nodeVersion: 20.19.5
    envVars:
      - key: NODE_ENV
        value: production